name: scan

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call /api/scan
        run: |
          echo "Pinging scan url..."
          curl -sS -L "${{ secrets.SCAN_URL }}" | head -c 500
